# NumPy - Linear Algebra Lib. for Python :

>**Installation :** `!conda install numpy` OR `!pip install numpy`

# NumPy Arrays :

In [4]:
my_list = [0,1,2,3,4]

In [5]:
#Importing numpy
import numpy as np

In [9]:
# casting a list into numpy array
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4])

In [14]:
my_matrix = [[1,2,3], [4,5,6], [7,8,9]]

# casting 2-D list into 2-D array
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## **Common ways to create NumPy arrays :**

**1. Creating array of specific range :**

In [19]:
# np.arange(start, end, step-size=1)
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

---

**2. Creating array of all zeros :**

In [68]:
# np.zeros(size)
np.zeros(3)

array([0., 0., 0.])

In [61]:
# n-D array of all zeros - np.zeros(n-sized_tuple) 
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

---

**3. Creating array of ones :**

In [69]:
# np.ones(size)
np.ones(5)

array([1., 1., 1., 1., 1.])

In [70]:
# n-D array of ones
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

---

**4. Creating linearly-spaced arrays in given range :**

In [73]:
# linspace(start, stop, even_space=50)
# even_space - the size of array (also generates the array from start-stop range only)      
np.linspace(0,10, 8)

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        ])

---

**5. IDENTITY MATRIX using numpy (size - n * n) :**

In [74]:
# np.eye(size)
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

---

### **6. Arrays of random numbers :**

In [107]:
# 1. rand - gives random numbers in uniform distribution (range : 0-1)
np.random.rand(5)
# for 2-D >  np.random.rand(3,5)

array([0.44189654, 0.15263331, 0.1320879 , 0.34890858, 0.94540165])

In [116]:
# 2. randn - gives random numbers in standard normal distribution
np.random.randn(5)
# for 2-D >  np.random.rand(3,5)

array([-2.13179588,  1.96873073,  0.28161955,  1.35750393,  1.55395604])

In [122]:
# 3. randint - 
   # np.random.randint(low_inclusive, high_exlcusive, size=1)

np.random.randint(0,100)    

36

In [124]:
np.random.randint(0,100, 10)

array([72, 20, 76, 18, 28, 85, 60, 69, 67, 52])

---