# NumPy - Linear Algebra Lib. for Python :

>**Installation :** `!conda install numpy` OR `!pip install numpy`

# NumPy Arrays :

In [1]:
my_list = [0,1,2,3,4]

In [2]:
#Importing numpy
import numpy as np

In [3]:
# casting a list into numpy array
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4])

In [4]:
# casting a list into numpy array with specific data type
# to make it more efficient
myarr = np.array(my_list, np.int8)
myarr

array([0, 1, 2, 3, 4], dtype=int8)

In [5]:
# While giving specific data type if value exceeds than it will give error
np.array([1,23,7878887,3,4], np.int8)

array([  1,  23, -25,   3,   4], dtype=int8)

In [6]:
my_matrix = [[1,2,3], [4,5,6], [7,8,9]]

# casting 2-D list into 2-D array
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## **Common ways to create NumPy arrays :**

**1. Creating array of specific range :**

In [7]:
# np.arange(start, end, step-size=1)
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

---

**2. Creating array of all zeros :**

In [9]:
# np.zeros(size)
np.zeros(3)

array([0., 0., 0.])

In [10]:
# n-D array of all zeros - np.zeros(n-sized_tuple) 
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

---

**3. Creating array of ones :**

In [11]:
# np.ones(size)
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
# n-D array of ones
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

---

**4. Creating linearly-spaced arrays in given range :**

In [13]:
# linspace(start, stop, even_space=50)
# even_space - the size of array (also generates the array from start-stop range only)      
np.linspace(0,10, 8)

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        ])

---

**5. IDENTITY MATRIX using numpy (size - n * n) :**

In [22]:
# np.eye(size)
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
# np.identity(size)
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

---

### **6. Arrays of random numbers :**

In [15]:
# 1. rand - gives random numbers in uniform distribution (range : 0-1)
np.random.rand(5)
# for 2-D >  np.random.rand(3,5)

array([0.70623777, 0.35468481, 0.91732787, 0.35789881, 0.28021821])

In [16]:
# 2. randn - gives random numbers in standard normal distribution
np.random.randn(5)
# for 2-D >  np.random.rand(3,5)

array([-2.13984792,  0.10133002, -0.55130326, -0.53773865,  1.05124847])

In [17]:
# 3. randint - 
   # np.random.randint(low_inclusive, high_exlcusive, size=1)

np.random.randint(0,100)    

0

In [18]:
np.random.randint(0,100, 10)

array([36, 73, 97, 67, 82, 97, 84, 57, 37, 41])

---

### **7. Creating Empty Array :**

In [19]:
temparr = np.ones(5)
temparr.size

5

In [20]:
# creates empty array
emparr = np.empty((2,2))
emparr

array([[5.e-324, 0.e+000],
       [0.e+000, 0.e+000]])

In [21]:
# creates empty array of specific sized predefined array (empty_like)
# replicates the size of existing array
emp_like = np.empty_like(temparr)
emp_like

array([-2.13984792,  0.10133002, -0.55130326, -0.53773865,  1.05124847])

---