# More Arrays METHODS and ATTRIBUTES :

In [83]:
import numpy as np

In [84]:
arr = np.arange(0,25)
ranarr = np.random.randint(0,50, 27)

In [85]:
print('arr = ',arr)
print('ranarr = ',ranarr)

arr =  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
ranarr =  [ 5 27 27  4  8 44 48  8 40 44  5 40 33 33  3 15 22 27 14  6 30 42 14 38
 30  5 18]


---

### 1. Reshaping array (i.e. 1-D to n-D) (Method) :

> *syntax :* `arrayName.reshape(n - rows, m - columns, ... )`

In [86]:
# 1-D to 2-D
arr_2d = arr.reshape(5,5)

#     here, multiplication of arguments in reshape() should be always 
#           equal to the size of 1-D array (base_array) & vice-versa
#     error arises when above conditions are not followed
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [87]:
# 1-D to 3-D
ranarr.reshape(3,3,3)

array([[[ 5, 27, 27],
        [ 4,  8, 44],
        [48,  8, 40]],

       [[44,  5, 40],
        [33, 33,  3],
        [15, 22, 27]],

       [[14,  6, 30],
        [42, 14, 38],
        [30,  5, 18]]])

In [88]:
# 2-D to 1-D   ->   n*m (2-D size) = N (1-D size)
arr_2d.reshape(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

---

### 2. Finding Max. and Min. value in array (Method) :
`.min()`/`.max()`

In [89]:
arr.min()

0

In [90]:
ranarr.max()

48

---

### 3. Finding *INDEX* of Max. and Min. value in array (Method) : 
`.argmin()`/`.argmax()`

In [91]:
arr.argmax()   # returns index

24

In [92]:
ranarr.argmin()

14

---

### 3. Finding *SHAPE* of array/vector  (Attribute) : 
`arrayName.shape` - returns tuple

In [99]:
arr.shape

(25,)

In [100]:
arr_2d.shape

(5, 5)

In [101]:
ranarr.reshape(3,3,3).shape

(3, 3, 3)

---

### 4. Finding DATA TYPE (Attribute) :
`arrayName.dtype`

In [111]:
arr.dtype

dtype('int32')

In [118]:
np.array([1.2,2.2,0.0,12.1024564]).dtype

dtype('float64')

In [119]:
np.array(['0',1,2,4,"efe"]).dtype

dtype('<U11')

---