# More Arrays METHODS and ATTRIBUTES :

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,25)
ranarr = np.random.randint(0,50, 27)

In [3]:
print('arr = ',arr)
print('ranarr = ',ranarr)

arr =  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
ranarr =  [22 25 13 46 35 38 17  3 33 19 15 43 31 31 42 49 30 45  5  9 19 11 15 32
 28  1  0]


---

### 1. Reshaping array (i.e. 1-D to n-D) (Method) :

> *syntax :* `arrayName.reshape(n - rows, m - columns, ... )`
>  and `arrayName.ravel()` - n-D array to 1-D array

In [4]:
# 1-D to 2-D
arr_2d = arr.reshape(5,5)

#     here, multiplication of arguments in reshape() should be always 
#           equal to the size of 1-D array (base_array) & vice-versa
#     error arises when above conditions are not followed
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [5]:
# 1-D to 3-D
ranarr.reshape(3,3,3)

array([[[22, 25, 13],
        [46, 35, 38],
        [17,  3, 33]],

       [[19, 15, 43],
        [31, 31, 42],
        [49, 30, 45]],

       [[ 5,  9, 19],
        [11, 15, 32],
        [28,  1,  0]]])

In [6]:
# 2-D to 1-D   ->   n*m (2-D size) = N (1-D size)
arr_2d.reshape(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [7]:
arrRavel = np.copy(arr_2d)
arrRavel

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [8]:
# from n-D array to 1-D array using ravel() function
arrRavel_1d = arrRavel.ravel()
arrRavel_1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

---

### 2. Finding Max. and Min. value in array (Method) :
`.min()`/`.max()`

In [9]:
arr.min()

0

In [10]:
ranarr.max()

49

---

### 3. Finding *INDEX* of Max. and Min. value in array (Method) : 
`.argmin()`/`.argmax()`

In [11]:
arr.argmax()   # returns index

24

In [12]:
ranarr.argmin()

26

---

### 4. Sorting an array :
`.sort()`

In [29]:
sortedArr = np.array([1,4,2,6,33,5])
sortedArr.sort()
sortedArr

array([ 1,  2,  4,  5,  6, 33])

---

### 4.  Using `.argsort()` :

>***.argsort() function gives the order in which a given array must be arranged for ascending order, it returns the index number of elements present in an array***

In [36]:
one = np.array([1,3,324,54,6])
one

array([  1,   3, 324,  54,   6])

In [59]:
# gives indices of the given array to be sorted
one.argsort()

array([0, 1, 4, 3, 2], dtype=int64)

---

In [44]:
#using argsort() in 2-D arrays using axis 

In [79]:
two = np.array([[1, 2, 3], [4, 5, 6], [7, 1, 0]])
two

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [80]:
two.max(axis=0)

array([7, 5, 6])

In [81]:
two.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [82]:
two.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [83]:
two.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [78]:
# two.sort(axis=0)
# two

array([[1, 1, 0],
       [4, 2, 3],
       [7, 5, 6]])

In [84]:
two.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

---

### 5. Finding *SHAPE* of array/vector  (Attribute) : 
`arrayName.shape` - returns tuple

In [15]:
arr.shape

(25,)

In [16]:
arr_2d.shape

(5, 5)

In [17]:
ranarr.reshape(3,3,3).shape

(3, 3, 3)

---

### 6. Finding DATA TYPE (Attribute) :
`arrayName.dtype`

In [18]:
arr.dtype

dtype('int32')

In [19]:
np.array([1.2,2.2,0.0,12.1024564]).dtype

dtype('float64')

In [20]:
np.array(['0',1,2,4,"efe"]).dtype

dtype('<U11')

---