# NumPy Indexing and Selection : 

In [1]:
import numpy as np

In [8]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

> **Indexing is somewhat similar to python list**

In [10]:
arr[8]

8

> **Slice notation can also be used in arrays same as list**

`arrayName[start : stop : steps]`

In [19]:
arr[3:7]

array([3, 4, 5, 6])

In [18]:
arr[2:9:2]

array([2, 4, 6, 8])

In [46]:
arr[:5]

array([0, 1, 2, 3, 4])

> **NumPy array can Broadcast while list cannot**

`arrayName[start:stop:steps] = value`

In [47]:
arr[0:5] = 100

In [48]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [49]:
arr = np.arange(0,11) #resetting an array
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
slice_of_arr = arr[0: int(len(arr)/2)]
slice_of_arr

array([0, 1, 2, 3, 4])

> **NOTE :** *Changing an element of child array can result into changing of parent array also*

- This happens because the data is not copied but is reused, NumPy does that in order to avoid memory issues of very large arrays. 

In [51]:
slice_of_arr[:] = 100
slice_of_arr

array([100, 100, 100, 100, 100])

In [52]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [53]:
# arr = np.arange(0,11)
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

> **In order to copy an array copy() function is used :**

`arrayName.copy()`

In [55]:
arr_copy = arr.copy()
arr_copy

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [59]:
# Changing arr_copy will not change arr because it created a copy
arr_copy[:] = 1000
arr_copy

array([1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [60]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])