# Indexing a Matrix (2-D Array) :

In [1]:
import numpy as np

In [2]:
arr_2d = np.array([[5,10,15], [20,25,30], [35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

## Two Formats of Grabbing Value from Matrix :

### **1. Double Bracket Format :** 

In [5]:
arr_2d[0]

array([ 5, 10, 15])

In [7]:
arr_2d[1][2]

30

### **2. Single Bracket Format :** (recommended)

In [8]:
arr_2d[2,1]

40

---

### Colon ( : ) can be use to slice certain portion of the matrices:

In [9]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [13]:
arr_2d[:, 1:]

array([[10, 15],
       [25, 30],
       [40, 45]])

In [14]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [12]:
# Grabbing top right (2 x 2) Matrix
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

---

In [16]:
array_2d = np.arange(50).reshape(5,10)
array_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [17]:
array_2d[1:3, 3:5]

array([[13, 14],
       [23, 24]])