# Conditional Selection Method :

In [1]:
import numpy as np

In [2]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
# To get array of boolean value
bool_arr = arr > 5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [4]:
# Todo conditional selection
# That Boolean array can be used to select elements from the original
#      array conditinally

In [5]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [6]:
# Most Important

arr[arr<5]

array([1, 2, 3, 4])

---

## Finding an element in an array :
`np.where(args/conditions)`:

In [7]:
arr_2d = np.arange(9).reshape(3,3)
arr_2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
np.where(arr_2d == 5)

(array([1], dtype=int64), array([2], dtype=int64))

In [13]:
type(np.where(arr_2d == 5))

tuple

In [14]:
np.where(arr_2d > 5)

(array([2, 2, 2], dtype=int64), array([0, 1, 2], dtype=int64))

In [15]:
# It returns the tuple saying the location of elements according to 
# the given conditions