# Conditional Selection Method :

In [2]:
import numpy as np

In [4]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
# To get array of boolean value
bool_arr = arr > 5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [12]:
# Todo conditional selection
# That Boolean array can be used to select elements from the original
#      array conditinally

In [17]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [19]:
# Most Important

arr[arr<5]

array([1, 2, 3, 4])

---