# NumPy Operations : 
***(same as Matrix operations)***

- **Array with Array**
- **Array with Scalars**
- **Universal Array Functions**

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


>**1. Array with Array Operations:**

In [3]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [4]:
arr * arr 
# ....etc all operations

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

>**2. Array with Scalars Operations:**

In [5]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [6]:
arr - 100 

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [7]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [8]:
# IMP - Normal one gives ERROR
1/0

ZeroDivisionError: division by zero

In [ ]:
# NumPy only Gives WARNING
# first element -> 0/0 , O?P -> nan
arr / arr

In [9]:
# first element -> 1/0 , O/P -> inf
1 / arr

C:\Users\ABCD\AppData\Local\Temp/ipykernel_21416/2473141178.py:2: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

---

>**2. Universal Array Functions:**

In [10]:
# 1. Square root of every elements
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [13]:
# 2. Calculating Exponential of every elements ()
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [27]:
# 3. Finding Maximum/Minimum element
np.max(arr)
# np.min(arr)
    #OR
arr.max()
# arr.min()

0

In [16]:
# 4. Performing Trigonometric Operations on every element
np.sin(arr)
np.cos(arr)
#     ......etc

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153])

In [18]:
# 5. Performing LOGARITHMATIC Operations on every element
np.log(arr)

C:\Users\ABCD\AppData\Local\Temp/ipykernel_21416/3553873897.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [21]:
# 5. Finding Sum of every Elements
np.sum(arr)
#OR 
arr.sum()

55

In [22]:
# 6. Finding Standard Deviation
np.std(arr)
#OR
arr.std()

3.1622776601683795

---

In [23]:
arr_2d = np.arange(1,26).reshape(5,5)
arr_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# Getting the sum of all the columns in arr_2d

In [26]:
# Here axis=0, means all the columns
# axis=1, means all the rows

np.sum(arr_2d, axis=0)
# OR
arr_2d.sum(axis=0)

array([55, 60, 65, 70, 75])

---

# Many more [Universal Array Functions 😁](https://numpy.org/doc/stable/reference/ufuncs.html)