# NumPy Axis :

In [1]:
import numpy as np

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr_2d = arr.reshape(2,5)
arr_2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [4]:
arr_3d = np.arange(27).reshape(3, 3, 3)
arr_3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

**1. Here, an array *'arr'* is 1-D array so it has *[axis=0]*.**

**2. Here, an array *'arr_2d* is 2-D array so it has *[axis=0,axis=1]*.**

- **axis = 0**, here represents **rows** (i.e. r1,r2,r3,...)
- **axis = 1**, here represents **columns** (i.e. c1,c2,c3,...)

In [5]:
arr_2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [6]:
# USE of axis :
# Finding sum of elements of arr_2d in column wise
# i.e. sum at axis=0
arr_2d.sum(axis=0)

array([ 5,  7,  9, 11, 13])

In [7]:
# Finding sum of elements of arr_2d in row wise
# i.e. sum at axis=1
np.sum(arr_2d, axis=1)

array([10, 35])

In [8]:
# More examples

In [9]:
# step-deviation
arr_2d.std()

2.8722813232690143

In [10]:
# Column-wise step-deviation
arr_2d.std(axis=0)

array([2.5, 2.5, 2.5, 2.5, 2.5])

In [11]:
# row-wise step-deviation
arr_2d.std(axis=1)

array([1.41421356, 1.41421356])

---

In [15]:
# Extras
arr_3d.sum(axis=2)

array([[ 3, 12, 21],
       [30, 39, 48],
       [57, 66, 75]])