# Few More Important Methods on NumPy :

In [1]:
import numpy as np

In [2]:
arr = np.arange(9)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [3]:
arr_2d = arr.reshape(3,3)
arr_1x9 = arr.reshape(1,9)
arr_2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

---

## 1. Transpose of Matrix : 

In [4]:
arr_2d.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [5]:
# It does not applies on 1-D array
arr.T

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
arr_1x9.T

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

---
## 2. Fetcing iterator using *.flat* attribute :

In [7]:
arr.flat

In [8]:
for item in arr.flat:
    print(item)

0
1
2
3
4
5
6
7
8


---
## 3. Finding Number of dimensions using *ndim* :

In [9]:
arr.ndim

1

In [10]:
arr_2d.ndim

2

---
## 4. Finding the bytes of array :

In [11]:
arr.nbytes

36

In [12]:
np.arange(0,15).nbytes

60

In [13]:
np.random.rand(1).nbytes

8

In [14]:
np.random.randint(1,6, 1)

array([1])

In [15]:
np.random.randint(1,6, 1).nbytes

4

---
## 5. Finding Number of non-zero elements :

In [24]:
nonZeroArr = np.array([0,1,2,0,4,0,5,6,7])
nonZeroArr_2d = nonZeroArr.reshape(3,3)
nonZeroArr.size

9

In [26]:
# Counts the number of non-zeros
np.count_nonzero(nonZeroArr)

6

In [29]:
# Gives the tuple representing dimensions that have non-zeros
np.nonzero(nonZeroArr)

(array([1, 2, 4, 6, 7, 8], dtype=int64),)

In [31]:
# Gives the tuple representing dimensions that have non-zeros
print(nonZeroArr_2d)
np.nonzero(nonZeroArr_2d)

[[0 1 2]
 [0 4 0]
 [5 6 7]]


(array([0, 0, 1, 2, 2, 2], dtype=int64),
 array([1, 2, 1, 0, 1, 2], dtype=int64))

---
## 6. NumPy Array to list :
`.tolist()`

In [33]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [34]:
arr.tolist()

[0, 1, 2, 3, 4, 5, 6, 7, 8]

---

# Many more [Attributes and Methods](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html) 😁